I got this to a semi workable state, still need to work on the object mask and result handling
Last error :

a _objectType:SoftLayer_Hardware,SoftLayer_Ticket,SoftLayer_Virtual_Guest
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/SoftLayer-3.0.2-py2.6.egg/SoftLayer/CLI/core.py", line 174, in main
    data = runnable.execute(command_args)
  File "/Library/Python/2.6/site-packages/SoftLayer-3.0.2-py2.6.egg/SoftLayer/CLI/modules/search.py", line 47, in execute
    for result in results:
TypeError: 'NoneType' object is not iterable